export const theme = {
  light: {
    theme: "light",
    primaryText: "#151419",
    primaryBg: "#fff",
    secondaryText: "#abaeae",
    secondaryBg: "#f7f7f7",
    activeColor: "#ffccd1",
    buttonColor: "#0a113d",
    buttonText: "#fff",
    cardText: "#151419",
    progressColor: "#0a113d",
    navButtonColor: "#0a113d",
    navButtonActiveColor: "#ffccd1",
  },
  dark: {
    theme: "dark",
    primaryText: "#f2f2f4",
    primaryBg: "#161b21",
    secondaryText: "#abaeae",
    secondaryBg: "#f7f7f7",
    activeColor: "#ffccd1",
    buttonColor: "#ffccd1",
    buttonText: "#1b1b1d",
    cardText: "#151419",
    progressColor: "#0a113d",
    navButtonColor: "#f7f7f7",
    navButtonActiveColor: "#ffccd1",
  },
};
